### ISSUE TITLE
Friends aren't importing correctly from Facebook.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#140]
We believe that we aren't importing Facebook friends correctly.

Locally, we need to:

1.  Confirm we import each friend correctly. We can do this with one HTTP request by sending a complete friend object payload.
2. Confirming success or failure of the HTTP Post.
3. Verbose logging that the above has been successful / unsuccessful
4. If unsuccessful, try 3 times in total. If after three times, log unsuccessful with as much info as possible.
5. On success, update firebase node /completedFriends with the {userID: true} via a push (so a uuid is created);

**Comment by jcampbell05** [comment]
@alexsup  It appears that when the Importing Friends screen was added the restriction on how many friends we imported at once was unrestricted so it tries to do as many as possible.

I believe this was due to the fact it was perceived to take a long time (especially over poor internet and with Rich).

This seems to oversaturate the network stack and cause it to not add people as friends (or at least feel like it hasn't done this yet). I added a `concat` to test if adds friends any quicker and I was able to see that I had at least 10 friends by the time I reached the on-boarding screens (it was 0 before).

I am looking into why exactly `concat` works and if it is the best solution for the user. This also could be causing https://github.com/Supmenow/sup-ios-issues/issues/141

**Comment by jcampbell05** [comment]
@alexsup so `concat`eventually adds my friends, however if the user kills the app before we are able to finish or there is a network error then we still fail to import everyone.

There are a few ways to solve this or enhance this in the future:
- Keep using `concat` for now - Will take a while to import friends and user can interrupt it.
- Trigger the import every time the app opens - Very consuming and we will have to re-start the list again which can still be interrupted by the user.
- Figure out if we can import more friends at once - Would speed up the import process, however if done incorrectly we will end up with the bug again.
- Move to HTTP importing - importing can continue to run in the background but adds additional complexity to the app since we need to coordinate importing users.
- Move it to the server - Requires a bit more work to implement the API call but all of the process of adding people as a friend can be move there where it can hopefully be faster and keep track of whats new.

**Comment by alexsup** [comment]
@jcampbell05 OK.

Importing friends is non-required functionality and should not interupt user experience nor should it be interrupted.

I imagine it should be done in the background.

I imagine that the process must be stateful and know if it has completed. If not, try again next time. However, it should be done incrementally so that if 30% of users are imported then the remaining 70% would be attempted next time and so on.

However, a simpler option would be to:

1. Get all friends.
2. Save to friendsQueue
3. Server deals with it.

**Comment by jcampbell05** [comment]
@alexsup For me the main concern is adding a lot of complexity to the app just to track where in the queue we are importing users from.

Right now we don't need this sort of functionally elsewhere in the app, so would like to avoid building it if we could. 

From my understanding the Server already has to track updates from firebase etc so I think would be in a better position to do this sort of thing and it would have the advantage of removing the need for both android and iOS to build it.

**Comment by jcampbell05** [comment]
Proposal for friendsImportQueue
https://supmenow.atlassian.net/wiki/display/SUP/Firebase+Macro+Schema

**Comment by jcampbell05** [comment]
@alexsup When are you thinking to implement the listener ? Would this be in the Node section ?

**Comment by alexsup** [comment]
@jcampbell05 ASAP. Simply because it's broken otherwise.

**Comment by jcampbell05** [comment]
@alexsup well we're just back to the original behaviour pre-June the 14th right now.

**Comment by alexsup** [comment]
@jcampbell05 please can you point to Jira story or issue that required this to be changed at that time?

**Comment by jcampbell05** [comment]
@alexsup I can't find one, off the top of my head we had introduced the new importing friends screen whilst I was away.

I think at the time we couldn't release until we sped up that screen to an acceptable standard. If this was something we needed to today we would take a screenshot and send it to buglife, it would be filed in github issues and we would figure out how we need to do it. 

We removed the `concat` to make it async, since it was pointed out that Android was able to do it not one-by-one. At the time I remember us being worried about it saturating the network stack so we tested it. It appeared to work but I think that is due to Runway east having good Wi-Fi, we may have tested it on 4G but it seems that even that is better in that building (Boosted?).

In real-life however it breaks due to saturation.

So we can prevent this in the future by:
- Continuing our Buglife -> Github Issues flow (I always ask someone who tries to mention an issue even if it's you :P to take a screenshot and report it)
- Start empathetically testing, Poor Network and Worst Device our users would have.
- We always had unit tests for this but we could add ones for making sure the network isn't saturated (By checking the order of requests and there aren't too many)

Anyways :) lets fix this for the future.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan Ok. This is a classic example of lack of team-work and communication. 

This clearly wasn't thought about, discussed or executed properly.

The outcome is that instead of the app not working for edge cases. It didn't work for everyone.

Now we can see the consequences of lack of team-work and communication let's be better.

**Comment by jcampbell05** [comment]
@alexsup  I think the Github issues on the whole have helped with some of the more recent issues as Buglife allows users experiencing issues to give us quick and easy feedback (Like when I'm testing on my journey home I can easily send a screenshot without having to remember the details)

**Comment by alexsup** [comment]
I accept that James. 

However, do you understand what I'm getting at?

You guys have to be more accountable to each other.

**Comment by jcampbell05** [comment]
@alexsup  yes.

**Comment by alexsup** [comment]
@jcampbell05 Thanks dude

**Comment by jcampbell05** [comment]
@alexsup Started work on this, working with @juliensup and @roger-tan to make sure its implemented the same as Android and other places we've hit the API in iOS.

**Comment by jcampbell05** [comment]
Implemented in 4.6 which is now released.
