### ISSUE TITLE
App is too big (in mb)

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#29]
Can we compress better or remove bloat?

**Comment by jcampbell05** [comment]
@alexsup So before we discuss what we can remove, we should figure out what the "target size" should be.

Is the app you are referring to the one on the app store or crashlytics ? And what size would be idea?

**Comment by alexsup** [comment]
App Store.

25 MB

**Comment by roger-tan** [comment]
We can clean up at least old assets we don't use.

**Comment by jcampbell05** [comment]
So there are a few things we can do:
- Remove old assets we don't use.
- Compress the assets ourselves rather than relying on Xcode's compression. (Read this https://imageoptim.com/tweetbot.html)
- Reduce the quality of some assets (Images often hold more colour and quality than most people can discern on a mobile phone)
- Improve the way we design the app so more of it can be rendered in code without assets.
- Decrease the duplication of assets in our designs so we don't need 5 different types of icons.
- Remove libraries we don't need or are overkill (i.e Using Parse just for notifications and the library we only use just to show a tick after the user shares Sup via social media).
- Simplify the app by focusing and DRY.

**Comment by alexsup** [comment]
OK. Let's point this to V5.x

**Comment by jcampbell05** [comment]
The new Firebase SDK should help us reduce this :)

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan moved to Jira. Not an issue.
